// examples/vue-demo/src/App.vue
<template>
  <div class="app">
    <h1>🚀 Lottie Vue Demo</h1>
    
    <div class="demo-grid">
      <!-- 基础组件示例 -->
      <div class="demo-card">
        <h2>基础组件示例</h2>
        <Lottie
          :animation-data="animationData"
          :loop="true"
          :autoplay="isPlaying"
          :speed="speed"
          class="lottie-container"
          @ready="onReady"
          @complete="onComplete"
        />
        <div class="controls">
          <button @click="isPlaying = !isPlaying">
            {{ isPlaying ? '暂停' : '播放' }}
          </button>
          <button @click="speed += 0.5">加速 ({{ speed }}x)</button>
          <button @click="speed = Math.max(0.5, speed - 0.5)">减速</button>
        </div>
      </div>
      
      <!-- Hook 示例 -->
      <HookDemo />
      
      <!-- 交互式示例 -->
      <InteractiveDemo />
      
      <!-- Ref 控制示例 -->
      <RefDemo />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Lottie } from '@ldesign/lottie-vue'
import HookDemo from './components/HookDemo.vue'
import InteractiveDemo from './components/InteractiveDemo.vue'
import RefDemo from './components/RefDemo.vue'
import animationData from './animation.json'

const isPlaying = ref(true)
const speed = ref(1)

const onReady = () => {
  console.log('Animation ready!')
}

const onComplete = () => {
  console.log('Animation completed!')
}
</script>

<style scoped>
.app {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
}

h1 {
  text-align: center;
  margin-bottom: 40px;
  color: #1a1a1a;
  font-size: 2.5rem;
}

.demo-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 30px;
}

.demo-card {
  background: white;
  border-radius: 12px;
  padding: 24px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.08);
}

.demo-card h2 {
  font-size: 1.25rem;
  margin-bottom: 20px;
  color: #444;
}

.lottie-container {
  width: 100%;
  height: 250px;
  background: #f9f9f9;
  border-radius: 8px;
  margin-bottom: 16px;
}

.controls {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
}

.controls button {
  padding: 10px 20px;
  border: none;
  border-radius: 8px;
  background: #42b983;
  color: white;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.controls button:hover {
  background: #33a06f;
}
</style>

// examples/angular-demo/src/app/app.component.ts
import { Component } from '@angular/core';
import { LottieComponent } from '@ldesign/lottie-angular';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [LottieComponent],
  template: `
    <div class="container">
      <h1>Angular Lottie Demo</h1>
      
      <div class="demo-section">
        <h2>Basic Animation</h2>
        <lottie
          path="https://lottie.host/4db68bbd-31f6-4cd8-84eb-189de081159a/IGmMCqhzpt.json"
          [autoplay]="true"
          [loop]="true"
          [style.width.px]="300"
          [style.height.px]="300"
        />
      </div>

      <div class="demo-section">
        <h2>Controlled Animation</h2>
        <lottie
          #lottieAnimation
          path="https://lottie.host/4db68bbd-31f6-4cd8-84eb-189de081159a/IGmMCqhzpt.json"
          [autoplay]="false"
          [loop]="true"
          [style.width.px]="300"
          [style.height.px]="300"
          (complete)="onComplete()"
        />
        <div class="controls">
          <button (click)="lottieAnimation.play()">Play</button>
          <button (click)="lottieAnimation.pause()">Pause</button>
          <button (click)="lottieAnimation.stop()">Stop</button>
        </div>
      </div>

      <div class="demo-section">
        <h2>Speed Control</h2>
        <lottie
          #speedAnimation
          path="https://lottie.host/4db68bbd-31f6-4cd8-84eb-189de081159a/IGmMCqhzpt.json"
          [autoplay]="true"
          [loop]="true"
          [speed]="speed"
          [style.width.px]="300"
          [style.height.px]="300"
        />
        <div class="controls">
          <label>Speed: {{ speed }}x</label>
          <input 
            type="range" 
            min="0.1" 
            max="3" 
            step="0.1" 
            [value]="speed"
            (input)="onSpeedChange($event)"
          />
        </div>
      </div>
    </div>
  `,
  styles: [`
    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
      font-family: system-ui, -apple-system, sans-serif;
    }

    h1 {
      color: #333;
      text-align: center;
      margin-bottom: 2rem;
    }

    .demo-section {
      margin-bottom: 3rem;
      padding: 2rem;
      border: 1px solid #e0e0e0;
      border-radius: 8px;
      background: #f9f9f9;
    }

    h2 {
      color: #555;
      margin-bottom: 1rem;
    }

    lottie {
      display: block;
      margin: 0 auto;
    }

    .controls {
      display: flex;
      gap: 1rem;
      justify-content: center;
      margin-top: 1rem;
      flex-wrap: wrap;
    }

    button {
      padding: 0.5rem 1.5rem;
      background: #4CAF50;
      color: white;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 1rem;
      transition: background 0.3s;
    }

    button:hover {
      background: #45a049;
    }

    input[type="range"] {
      width: 200px;
      margin-left: 1rem;
    }

    label {
      display: flex;
      align-items: center;
    }
  `]
})
export class AppComponent {
  speed = 1;

  onComplete() {
    console.log('Animation completed!');
  }

  onSpeedChange(event: Event) {
    const target = event.target as HTMLInputElement;
    this.speed = parseFloat(target.value);
  }
}
