// packages/vue/src/components/Lottie.vue
<template>
  <div ref="containerRef" :class="className" :style="style"></div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted, computed } from 'vue'
import { createLottie, type ILottieInstance } from '@ldesign/lottie-core'
import type { LottieProps } from '../types'

const props = withDefaults(defineProps<LottieProps>(), {
  loop: true,
  autoplay: true,
  renderer: 'svg',
  quality: 'high',
  speed: 1,
  direction: 1
})

const emit = defineEmits<{
  ready: [instance: ILottieInstance]
  error: [error: Error]
  complete: []
  loopComplete: []
  enterFrame: [event: any]
  segmentStart: [event: any]
  destroy: []
}>()

const containerRef = ref<HTMLDivElement>()
const instance = ref<ILottieInstance | null>(null)

// 暴露实例和方法
defineExpose({
  instance: computed(() => instance.value),
  play: () => instance.value?.play(),
  pause: () => instance.value?.pause(),
  stop: () => instance.value?.stop(),
  goToAndPlay: (value: number, isFrame?: boolean) => {
    instance.value?.goToAndPlay(value, isFrame)
  },
  goToAndStop: (value: number, isFrame?: boolean) => {
    instance.value?.goToAndStop(value, isFrame)
  },
  setSpeed: (speed: number) => instance.value?.setSpeed(speed),
  setDirection: (direction: 1 | -1) => instance.value?.setDirection(direction),
  destroy: () => instance.value?.destroy(),
  getDuration: () => instance.value?.animation?.getDuration(),
  getCurrentFrame: () => instance.value?.animation?.currentFrame || 0,
  getTotalFrames: () => instance.value?.animation?.totalFrames || 0,
})

// 初始化
onMounted(() => {
  if (!containerRef.value) return

  const lottieInstance = createLottie({
    container: containerRef.value,
    animationData: props.animationData,
    path: props.path,
    loop: props.loop,
    autoplay: props.autoplay,
    renderer: props.renderer,
    quality: props.quality,
    speed: props.speed,
    direction: props.direction,
    ...props.config
  })

  instance.value = lottieInstance

  // 绑定事件
  lottieInstance.on('ready', () => emit('ready', lottieInstance))
  lottieInstance.on('error', (err: Error) => emit('error', err))
  lottieInstance.on('complete', () => emit('complete'))
  lottieInstance.on('loopComplete', () => emit('loopComplete'))
  lottieInstance.on('enterFrame', (e: any) => emit('enterFrame', e))
  lottieInstance.on('segmentStart', (e: any) => emit('segmentStart', e))
  lottieInstance.on('destroy', () => emit('destroy'))
})

// 监听属性变化
watch(() => props.loop, (loop) => {
  instance.value?.setLoop(loop)
})

watch(() => props.speed, (speed) => {
  instance.value?.setSpeed(speed)
})

watch(() => props.direction, (direction) => {
  instance.value?.setDirection(direction)
})

watch(() => props.autoplay, (autoplay) => {
  if (autoplay) {
    instance.value?.play()
  } else {
    instance.value?.pause()
  }
})

// 清理
onUnmounted(() => {
  instance.value?.destroy()
  instance.value = null
})
</script>

<script lang="ts">
export const Lottie = {
  name: 'Lottie'
}

export const LottiePlayer = Lottie
</script>

// packages/react/src/components/Lottie.tsx
import React, { forwardRef, useEffect, useImperativeHandle, useRef } from 'react'
import { createLottie, type ILottieInstance, type LottieConfig } from '@ldesign/lottie-core'
import type { LottieProps, LottieRef } from '../types'

/**
 * Lottie React Component
 */
export const Lottie = forwardRef<LottieRef, LottieProps>(({
  animationData,
  path,
  loop = true,
  autoplay = true,
  renderer = 'svg',
  quality = 'high',
  speed = 1,
  direction = 1,
  className,
  style,
  onComplete,
  onLoopComplete,
  onEnterFrame,
  onSegmentStart,
  onReady,
  onError,
  onDestroy,
  ...restConfig
}, ref) => {
  const containerRef = useRef<HTMLDivElement>(null)
  const instanceRef = useRef<ILottieInstance | null>(null)

  useImperativeHandle(ref, () => ({
    get instance() {
      return instanceRef.current
    },
    play: () => instanceRef.current?.play(),
    pause: () => instanceRef.current?.pause(),
    stop: () => instanceRef.current?.stop(),
    goToAndPlay: (value: number, isFrame?: boolean) => {
      instanceRef.current?.goToAndPlay(value, isFrame)
    },
    goToAndStop: (value: number, isFrame?: boolean) => {
      instanceRef.current?.goToAndStop(value, isFrame)
    },
    setSpeed: (speed: number) => instanceRef.current?.setSpeed(speed),
    setDirection: (direction: 1 | -1) => instanceRef.current?.setDirection(direction),
    destroy: () => instanceRef.current?.destroy(),
    getDuration: () => instanceRef.current?.animation?.getDuration(),
    getCurrentFrame: () => instanceRef.current?.animation?.currentFrame || 0,
    getTotalFrames: () => instanceRef.current?.animation?.totalFrames || 0,
  }), [])

  useEffect(() => {
    if (!containerRef.current) return

    const config: LottieConfig = {
      container: containerRef.current,
      animationData,
      path,
      loop,
      autoplay,
      renderer,
      quality,
      speed,
      direction,
      ...restConfig
    }

    // 创建实例
    const instance = createLottie(config)
    instanceRef.current = instance

    // 绑定事件
    if (onComplete) instance.on('complete', onComplete)
    if (onLoopComplete) instance.on('loopComplete', onLoopComplete)
    if (onEnterFrame) instance.on('enterFrame', onEnterFrame)
    if (onSegmentStart) instance.on('segmentStart', onSegmentStart)
    if (onDestroy) instance.on('destroy', onDestroy)

    // 加载完成事件
    instance.on('ready', () => {
      onReady?.(instance)
    })

    // 错误事件
    instance.on('error', (error: Error) => {
      onError?.(error)
    })

    // 清理函数
    return () => {
      if (onComplete) instance.off('complete', onComplete)
      if (onLoopComplete) instance.off('loopComplete', onLoopComplete)
      if (onEnterFrame) instance.off('enterFrame', onEnterFrame)
      if (onSegmentStart) instance.off('segmentStart', onSegmentStart)
      if (onDestroy) instance.off('destroy', onDestroy)

      instance.destroy()
      instanceRef.current = null
    }
  }, [path, animationData]) // 只在动画源改变时重新创建

  // 更新属性
  useEffect(() => {
    if (!instanceRef.current) return
    instanceRef.current.setLoop(loop)
  }, [loop])

  useEffect(() => {
    if (!instanceRef.current) return
    instanceRef.current.setSpeed(speed)
  }, [speed])

  useEffect(() => {
    if (!instanceRef.current) return
    instanceRef.current.setDirection(direction)
  }, [direction])

  useEffect(() => {
    if (!instanceRef.current) return
    if (autoplay) {
      instanceRef.current.play()
    } else {
      instanceRef.current.pause()
    }
  }, [autoplay])

  return (
    <div
      ref={containerRef}
      className={className}
      style={style}
    />
  )
})

Lottie.displayName = 'Lottie'

// 别名导出
export const LottiePlayer = Lottie
